apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
        labels:
          app: influx
    spec:
      containers:
      - name: influx
        image: influxdb:1.8.10
        ports:
          - containerPort: 8086
        env:
          - name: INFLUXDB_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: influx-creds
                key: username
          - name: INFLUXDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influx-creds
                key: password
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "true"