# k8s/deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog
  labels:
    app: movie-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-catalog
  template:
    metadata:
        labels:
          app: movie-catalog
    spec:
      containers:
      - name: server
        image: mohammadgh99/netflix_movie_catalog:0.0.1
        ports:
          - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/readiness"
            port: 8080
