# deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend
  labels:
    app: netflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
        labels:
          app: netflix-frontend
    spec:
      containers:
      - name: frontend
        image: mohammadgh99/netflix-frontend:v1.0.68
        ports:
          - containerPort: 3000
        env:
          - name: MOVIE_CATALOG_SERVICE
            value: "http://movie-catalog-service:8080"
          - name: REDIS_URL
            value: "redis-service.yaml:6379"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/"
            port: 3000
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/"
            port: 3000